# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# obs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: yarn install
#             - run: yarn run test
# workflows:
#   build-and-test:
#     jobs:
#       - build-and-test
version: 2
jobs:
  build:
    # Primary container image where all commands run

    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test

      # Service container image

      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference

      - image: circleci/redis:6.2-rc2-alpine3.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: sudo apt-get install redis-server-9.6
      - run: whoami
      - run: sudo service redis-server start
      # |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "CREATE TABLE test (name char(25));"
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "SELECT * from test"
